version: "3.8"

services:
  # =======================
  # Backend (FastAPI)
  # =======================
  backend:
    build: ./alpha-backend
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      # fallbacks if .env not set
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333
    depends_on:
      postgres:
        condition: service_healthy
      qdrant:
        condition: service_started
    restart: unless-stopped
    volumes:
      - ./alpha-backend:/app
    networks:
      - cv-network
    healthcheck:
      # no curl in image; use stdlib python to check /api/health
      test: ["CMD", "python", "-c", "import urllib.request, json, sys; resp=urllib.request.urlopen('http://localhost:8000/api/health', timeout=5); data=json.loads(resp.read().decode()); sys.exit(0 if data.get('status') in ('healthy','degraded') else 1)"]
      interval: 30s
      timeout: 8s
      retries: 5
      start_period: 40s

  # =======================
  # Frontend (Next.js)
  # =======================
  frontend:
    build: ./cv-analyzer-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    environment:
      # Expose the backend URL to the browser (through nginx proxy)
      NEXT_PUBLIC_API_URL: "https://alphacv.alphadatarecruitment.ae"
      BACKEND_URL: "http://backend:8000"
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - cv-network

  # =======================
  # Postgres
  # =======================
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: cv_database
      POSTGRES_USER: cv_user
      POSTGRES_PASSWORD: cv_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - cv-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 20s

  # =======================
  # Qdrant
  # =======================
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped
    networks:
      - cv-network
    # (qdrant image doesn’t ship curl/wget; rely on service_started here)

  # =======================
  # Nginx
  # =======================
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/letsencrypt:ro
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_started
    restart: unless-stopped
    networks:
      - cv-network
    environment:
      - DOMAIN=alphacv.alphadatarecruitment.ae

  # =======================
  # Certbot for Let's Encrypt
  # =======================
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/conf:/etc/letsencrypt:rw
    depends_on:
      - nginx
    command: >-
      sh -c "trap exit TERM;
      while :; do
        certbot renew --webroot --webroot-path=/var/www/certbot --quiet --no-self-upgrade;
        sleep 12h & wait $${!};
      done;"

volumes:
  postgres_data:
  qdrant_data:

networks:
  cv-network:
    driver: bridge
