# ===========================================
# ULTIMATE PROMETHEUS CONFIGURATION
# Comprehensive monitoring for 16GB + GPU setup
# ===========================================

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'alpha-cv-cluster'
    environment: 'production'

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # ===========================================
  # PROMETHEUS SELF-MONITORING
  # ===========================================
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # ===========================================
  # BACKEND APPLICATION MONITORING
  # ===========================================
  - job_name: 'alpha-backend'
    static_configs:
      - targets: ['backend:8000']
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 5s

  # ===========================================
  # NGINX MONITORING
  # ===========================================
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
    scrape_interval: 15s
    metrics_path: /metrics

  # ===========================================
  # QDRANT MONITORING
  # ===========================================
  - job_name: 'qdrant'
    static_configs:
      - targets: ['qdrant:6333']
    scrape_interval: 15s
    metrics_path: /metrics

  # ===========================================
  # POSTGRESQL MONITORING
  # ===========================================
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:9187']
    scrape_interval: 30s
    metrics_path: /metrics

  # ===========================================
  # REDIS MONITORING
  # ===========================================
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:9121']
    scrape_interval: 15s
    metrics_path: /metrics

  # ===========================================
  # SYSTEM MONITORING (NODE EXPORTER)
  # ===========================================
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    metrics_path: /metrics

  # ===========================================
  # GPU MONITORING (NVIDIA SMI)
  # ===========================================
  - job_name: 'nvidia-gpu'
    static_configs:
      - targets: ['nvidia-exporter:9400']
    scrape_interval: 10s
    metrics_path: /metrics

  # ===========================================
  # CUSTOM APPLICATION METRICS
  # ===========================================
  - job_name: 'alpha-cv-metrics'
    static_configs:
      - targets: ['backend:8000']
    scrape_interval: 5s
    metrics_path: /api/metrics
    params:
      format: ['prometheus']

# ===========================================
# STORAGE CONFIGURATION
# ===========================================
storage:
  tsdb:
    retention.time: 7d
    retention.size: 1GB
    wal-compression: true

# ===========================================
# REMOTE WRITE (Optional - for external storage)
# ===========================================
# remote_write:
#   - url: "https://your-external-prometheus.com/api/v1/write"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"
