version: "3.9"

services:
  backend:
    build:
      context: .
    container_name: alpha-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - QDRANT_HOST=qdrant
      - POSTGRES_URI=postgresql://alphauser:alphapassword@postgres:5432/alphadb
    depends_on:
      - postgres
      - qdrant
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: alpha-backend-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: alphadb
      POSTGRES_USER: alphauser
      POSTGRES_PASSWORD: alphapassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant
    container_name: alpha-backend-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

volumes:
  postgres_data:
  qdrant_data:
